// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BleProxyMsg_Java.proto

package com.hqw.bleproxy.protocol;

public final class BleProxy {
  private BleProxy() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.hqw.bleproxy.protocol.ProxyMsgCmd}
   */
  public enum ProxyMsgCmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CONTROL = 1;</code>
     */
    CONTROL(0, 1),
    /**
     * <code>SCAN_RESULT = 2;</code>
     */
    SCAN_RESULT(1, 2),
    ;

    /**
     * <code>CONTROL = 1;</code>
     */
    public static final int CONTROL_VALUE = 1;
    /**
     * <code>SCAN_RESULT = 2;</code>
     */
    public static final int SCAN_RESULT_VALUE = 2;


    public final int getNumber() { return value; }

    public static ProxyMsgCmd valueOf(int value) {
      switch (value) {
        case 1: return CONTROL;
        case 2: return SCAN_RESULT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProxyMsgCmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ProxyMsgCmd>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProxyMsgCmd>() {
            public ProxyMsgCmd findValueByNumber(int number) {
              return ProxyMsgCmd.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hqw.bleproxy.protocol.BleProxy.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProxyMsgCmd[] VALUES = values();

    public static ProxyMsgCmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ProxyMsgCmd(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.hqw.bleproxy.protocol.ProxyMsgCmd)
  }

  /**
   * Protobuf enum {@code com.hqw.bleproxy.protocol.ControlCmd}
   */
  public enum ControlCmd
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TURN_ON = 0;</code>
     */
    TURN_ON(0, 0),
    /**
     * <code>TURN_OFF = 1;</code>
     */
    TURN_OFF(1, 1),
    /**
     * <code>START_SCAN = 2;</code>
     */
    START_SCAN(2, 2),
    /**
     * <code>STOP_SCAN = 3;</code>
     */
    STOP_SCAN(3, 3),
    ;

    /**
     * <code>TURN_ON = 0;</code>
     */
    public static final int TURN_ON_VALUE = 0;
    /**
     * <code>TURN_OFF = 1;</code>
     */
    public static final int TURN_OFF_VALUE = 1;
    /**
     * <code>START_SCAN = 2;</code>
     */
    public static final int START_SCAN_VALUE = 2;
    /**
     * <code>STOP_SCAN = 3;</code>
     */
    public static final int STOP_SCAN_VALUE = 3;


    public final int getNumber() { return value; }

    public static ControlCmd valueOf(int value) {
      switch (value) {
        case 0: return TURN_ON;
        case 1: return TURN_OFF;
        case 2: return START_SCAN;
        case 3: return STOP_SCAN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ControlCmd>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ControlCmd>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ControlCmd>() {
            public ControlCmd findValueByNumber(int number) {
              return ControlCmd.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hqw.bleproxy.protocol.BleProxy.getDescriptor().getEnumTypes().get(1);
    }

    private static final ControlCmd[] VALUES = values();

    public static ControlCmd valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ControlCmd(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.hqw.bleproxy.protocol.ControlCmd)
  }

  public interface ControlOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.hqw.bleproxy.protocol.ControlCmd cmd = 1;
    /**
     * <code>required .com.hqw.bleproxy.protocol.ControlCmd cmd = 1;</code>
     */
    boolean hasCmd();
    /**
     * <code>required .com.hqw.bleproxy.protocol.ControlCmd cmd = 1;</code>
     */
    com.hqw.bleproxy.protocol.BleProxy.ControlCmd getCmd();
  }
  /**
   * Protobuf type {@code com.hqw.bleproxy.protocol.Control}
   */
  public static final class Control extends
      com.google.protobuf.GeneratedMessage
      implements ControlOrBuilder {
    // Use Control.newBuilder() to construct.
    private Control(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Control(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Control defaultInstance;
    public static Control getDefaultInstance() {
      return defaultInstance;
    }

    public Control getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Control(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.hqw.bleproxy.protocol.BleProxy.ControlCmd value = com.hqw.bleproxy.protocol.BleProxy.ControlCmd.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                cmd_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_Control_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_Control_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hqw.bleproxy.protocol.BleProxy.Control.class, com.hqw.bleproxy.protocol.BleProxy.Control.Builder.class);
    }

    public static com.google.protobuf.Parser<Control> PARSER =
        new com.google.protobuf.AbstractParser<Control>() {
      public Control parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Control(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Control> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.hqw.bleproxy.protocol.ControlCmd cmd = 1;
    public static final int CMD_FIELD_NUMBER = 1;
    private com.hqw.bleproxy.protocol.BleProxy.ControlCmd cmd_;
    /**
     * <code>required .com.hqw.bleproxy.protocol.ControlCmd cmd = 1;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.hqw.bleproxy.protocol.ControlCmd cmd = 1;</code>
     */
    public com.hqw.bleproxy.protocol.BleProxy.ControlCmd getCmd() {
      return cmd_;
    }

    private void initFields() {
      cmd_ = com.hqw.bleproxy.protocol.BleProxy.ControlCmd.TURN_ON;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, cmd_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmd_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hqw.bleproxy.protocol.BleProxy.Control parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.Control parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.Control parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.Control parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.Control parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.Control parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.Control parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.Control parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.Control parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.Control parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hqw.bleproxy.protocol.BleProxy.Control prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hqw.bleproxy.protocol.Control}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hqw.bleproxy.protocol.BleProxy.ControlOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_Control_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_Control_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hqw.bleproxy.protocol.BleProxy.Control.class, com.hqw.bleproxy.protocol.BleProxy.Control.Builder.class);
      }

      // Construct using com.hqw.bleproxy.protocol.BleProxy.Control.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmd_ = com.hqw.bleproxy.protocol.BleProxy.ControlCmd.TURN_ON;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_Control_descriptor;
      }

      public com.hqw.bleproxy.protocol.BleProxy.Control getDefaultInstanceForType() {
        return com.hqw.bleproxy.protocol.BleProxy.Control.getDefaultInstance();
      }

      public com.hqw.bleproxy.protocol.BleProxy.Control build() {
        com.hqw.bleproxy.protocol.BleProxy.Control result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hqw.bleproxy.protocol.BleProxy.Control buildPartial() {
        com.hqw.bleproxy.protocol.BleProxy.Control result = new com.hqw.bleproxy.protocol.BleProxy.Control(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hqw.bleproxy.protocol.BleProxy.Control) {
          return mergeFrom((com.hqw.bleproxy.protocol.BleProxy.Control)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hqw.bleproxy.protocol.BleProxy.Control other) {
        if (other == com.hqw.bleproxy.protocol.BleProxy.Control.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmd()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hqw.bleproxy.protocol.BleProxy.Control parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hqw.bleproxy.protocol.BleProxy.Control) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.hqw.bleproxy.protocol.ControlCmd cmd = 1;
      private com.hqw.bleproxy.protocol.BleProxy.ControlCmd cmd_ = com.hqw.bleproxy.protocol.BleProxy.ControlCmd.TURN_ON;
      /**
       * <code>required .com.hqw.bleproxy.protocol.ControlCmd cmd = 1;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.hqw.bleproxy.protocol.ControlCmd cmd = 1;</code>
       */
      public com.hqw.bleproxy.protocol.BleProxy.ControlCmd getCmd() {
        return cmd_;
      }
      /**
       * <code>required .com.hqw.bleproxy.protocol.ControlCmd cmd = 1;</code>
       */
      public Builder setCmd(com.hqw.bleproxy.protocol.BleProxy.ControlCmd value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.hqw.bleproxy.protocol.ControlCmd cmd = 1;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = com.hqw.bleproxy.protocol.BleProxy.ControlCmd.TURN_ON;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.hqw.bleproxy.protocol.Control)
    }

    static {
      defaultInstance = new Control(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.hqw.bleproxy.protocol.Control)
  }

  public interface ScanResultOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required string address = 2;
    /**
     * <code>required string address = 2;</code>
     */
    boolean hasAddress();
    /**
     * <code>required string address = 2;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>required string address = 2;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    // required int32 rssi = 3;
    /**
     * <code>required int32 rssi = 3;</code>
     */
    boolean hasRssi();
    /**
     * <code>required int32 rssi = 3;</code>
     */
    int getRssi();
  }
  /**
   * Protobuf type {@code com.hqw.bleproxy.protocol.ScanResult}
   */
  public static final class ScanResult extends
      com.google.protobuf.GeneratedMessage
      implements ScanResultOrBuilder {
    // Use ScanResult.newBuilder() to construct.
    private ScanResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ScanResult(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ScanResult defaultInstance;
    public static ScanResult getDefaultInstance() {
      return defaultInstance;
    }

    public ScanResult getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ScanResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              address_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              rssi_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_ScanResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_ScanResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hqw.bleproxy.protocol.BleProxy.ScanResult.class, com.hqw.bleproxy.protocol.BleProxy.ScanResult.Builder.class);
    }

    public static com.google.protobuf.Parser<ScanResult> PARSER =
        new com.google.protobuf.AbstractParser<ScanResult>() {
      public ScanResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ScanResult(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ScanResult> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string address = 2;
    public static final int ADDRESS_FIELD_NUMBER = 2;
    private java.lang.Object address_;
    /**
     * <code>required string address = 2;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string address = 2;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          address_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string address = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 rssi = 3;
    public static final int RSSI_FIELD_NUMBER = 3;
    private int rssi_;
    /**
     * <code>required int32 rssi = 3;</code>
     */
    public boolean hasRssi() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 rssi = 3;</code>
     */
    public int getRssi() {
      return rssi_;
    }

    private void initFields() {
      name_ = "";
      address_ = "";
      rssi_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRssi()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, rssi_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getAddressBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, rssi_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hqw.bleproxy.protocol.BleProxy.ScanResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.ScanResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.ScanResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.ScanResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.ScanResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.ScanResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.ScanResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.ScanResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.ScanResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.ScanResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hqw.bleproxy.protocol.BleProxy.ScanResult prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hqw.bleproxy.protocol.ScanResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hqw.bleproxy.protocol.BleProxy.ScanResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_ScanResult_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_ScanResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hqw.bleproxy.protocol.BleProxy.ScanResult.class, com.hqw.bleproxy.protocol.BleProxy.ScanResult.Builder.class);
      }

      // Construct using com.hqw.bleproxy.protocol.BleProxy.ScanResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        address_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        rssi_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_ScanResult_descriptor;
      }

      public com.hqw.bleproxy.protocol.BleProxy.ScanResult getDefaultInstanceForType() {
        return com.hqw.bleproxy.protocol.BleProxy.ScanResult.getDefaultInstance();
      }

      public com.hqw.bleproxy.protocol.BleProxy.ScanResult build() {
        com.hqw.bleproxy.protocol.BleProxy.ScanResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hqw.bleproxy.protocol.BleProxy.ScanResult buildPartial() {
        com.hqw.bleproxy.protocol.BleProxy.ScanResult result = new com.hqw.bleproxy.protocol.BleProxy.ScanResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.address_ = address_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.rssi_ = rssi_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hqw.bleproxy.protocol.BleProxy.ScanResult) {
          return mergeFrom((com.hqw.bleproxy.protocol.BleProxy.ScanResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hqw.bleproxy.protocol.BleProxy.ScanResult other) {
        if (other == com.hqw.bleproxy.protocol.BleProxy.ScanResult.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasAddress()) {
          bitField0_ |= 0x00000002;
          address_ = other.address_;
          onChanged();
        }
        if (other.hasRssi()) {
          setRssi(other.getRssi());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasAddress()) {
          
          return false;
        }
        if (!hasRssi()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hqw.bleproxy.protocol.BleProxy.ScanResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hqw.bleproxy.protocol.BleProxy.ScanResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required string address = 2;
      private java.lang.Object address_ = "";
      /**
       * <code>required string address = 2;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string address = 2;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string address = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string address = 2;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string address = 2;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000002);
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>required string address = 2;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        address_ = value;
        onChanged();
        return this;
      }

      // required int32 rssi = 3;
      private int rssi_ ;
      /**
       * <code>required int32 rssi = 3;</code>
       */
      public boolean hasRssi() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 rssi = 3;</code>
       */
      public int getRssi() {
        return rssi_;
      }
      /**
       * <code>required int32 rssi = 3;</code>
       */
      public Builder setRssi(int value) {
        bitField0_ |= 0x00000004;
        rssi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rssi = 3;</code>
       */
      public Builder clearRssi() {
        bitField0_ = (bitField0_ & ~0x00000004);
        rssi_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.hqw.bleproxy.protocol.ScanResult)
    }

    static {
      defaultInstance = new ScanResult(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.hqw.bleproxy.protocol.ScanResult)
  }

  public interface BleProxyMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required .com.hqw.bleproxy.protocol.ProxyMsgCmd cmd = 1;
    /**
     * <code>required .com.hqw.bleproxy.protocol.ProxyMsgCmd cmd = 1;</code>
     */
    boolean hasCmd();
    /**
     * <code>required .com.hqw.bleproxy.protocol.ProxyMsgCmd cmd = 1;</code>
     */
    com.hqw.bleproxy.protocol.BleProxy.ProxyMsgCmd getCmd();

    // optional .com.hqw.bleproxy.protocol.Control control = 2;
    /**
     * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
     */
    boolean hasControl();
    /**
     * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
     */
    com.hqw.bleproxy.protocol.BleProxy.Control getControl();
    /**
     * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
     */
    com.hqw.bleproxy.protocol.BleProxy.ControlOrBuilder getControlOrBuilder();

    // optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;
    /**
     * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
     */
    boolean hasScanResult();
    /**
     * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
     */
    com.hqw.bleproxy.protocol.BleProxy.ScanResult getScanResult();
    /**
     * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
     */
    com.hqw.bleproxy.protocol.BleProxy.ScanResultOrBuilder getScanResultOrBuilder();
  }
  /**
   * Protobuf type {@code com.hqw.bleproxy.protocol.BleProxyMsg}
   */
  public static final class BleProxyMsg extends
      com.google.protobuf.GeneratedMessage
      implements BleProxyMsgOrBuilder {
    // Use BleProxyMsg.newBuilder() to construct.
    private BleProxyMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BleProxyMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BleProxyMsg defaultInstance;
    public static BleProxyMsg getDefaultInstance() {
      return defaultInstance;
    }

    public BleProxyMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BleProxyMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.hqw.bleproxy.protocol.BleProxy.ProxyMsgCmd value = com.hqw.bleproxy.protocol.BleProxy.ProxyMsgCmd.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                cmd_ = value;
              }
              break;
            }
            case 18: {
              com.hqw.bleproxy.protocol.BleProxy.Control.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = control_.toBuilder();
              }
              control_ = input.readMessage(com.hqw.bleproxy.protocol.BleProxy.Control.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(control_);
                control_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              com.hqw.bleproxy.protocol.BleProxy.ScanResult.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = scanResult_.toBuilder();
              }
              scanResult_ = input.readMessage(com.hqw.bleproxy.protocol.BleProxy.ScanResult.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(scanResult_);
                scanResult_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_BleProxyMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_BleProxyMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg.class, com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<BleProxyMsg> PARSER =
        new com.google.protobuf.AbstractParser<BleProxyMsg>() {
      public BleProxyMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BleProxyMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BleProxyMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required .com.hqw.bleproxy.protocol.ProxyMsgCmd cmd = 1;
    public static final int CMD_FIELD_NUMBER = 1;
    private com.hqw.bleproxy.protocol.BleProxy.ProxyMsgCmd cmd_;
    /**
     * <code>required .com.hqw.bleproxy.protocol.ProxyMsgCmd cmd = 1;</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.hqw.bleproxy.protocol.ProxyMsgCmd cmd = 1;</code>
     */
    public com.hqw.bleproxy.protocol.BleProxy.ProxyMsgCmd getCmd() {
      return cmd_;
    }

    // optional .com.hqw.bleproxy.protocol.Control control = 2;
    public static final int CONTROL_FIELD_NUMBER = 2;
    private com.hqw.bleproxy.protocol.BleProxy.Control control_;
    /**
     * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
     */
    public boolean hasControl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
     */
    public com.hqw.bleproxy.protocol.BleProxy.Control getControl() {
      return control_;
    }
    /**
     * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
     */
    public com.hqw.bleproxy.protocol.BleProxy.ControlOrBuilder getControlOrBuilder() {
      return control_;
    }

    // optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;
    public static final int SCANRESULT_FIELD_NUMBER = 3;
    private com.hqw.bleproxy.protocol.BleProxy.ScanResult scanResult_;
    /**
     * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
     */
    public boolean hasScanResult() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
     */
    public com.hqw.bleproxy.protocol.BleProxy.ScanResult getScanResult() {
      return scanResult_;
    }
    /**
     * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
     */
    public com.hqw.bleproxy.protocol.BleProxy.ScanResultOrBuilder getScanResultOrBuilder() {
      return scanResult_;
    }

    private void initFields() {
      cmd_ = com.hqw.bleproxy.protocol.BleProxy.ProxyMsgCmd.CONTROL;
      control_ = com.hqw.bleproxy.protocol.BleProxy.Control.getDefaultInstance();
      scanResult_ = com.hqw.bleproxy.protocol.BleProxy.ScanResult.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCmd()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasControl()) {
        if (!getControl().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasScanResult()) {
        if (!getScanResult().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, cmd_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, control_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, scanResult_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, cmd_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, control_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, scanResult_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hqw.bleproxy.protocol.BleProxyMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.hqw.bleproxy.protocol.BleProxy.BleProxyMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_BleProxyMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_BleProxyMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg.class, com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg.Builder.class);
      }

      // Construct using com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getControlFieldBuilder();
          getScanResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cmd_ = com.hqw.bleproxy.protocol.BleProxy.ProxyMsgCmd.CONTROL;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (controlBuilder_ == null) {
          control_ = com.hqw.bleproxy.protocol.BleProxy.Control.getDefaultInstance();
        } else {
          controlBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (scanResultBuilder_ == null) {
          scanResult_ = com.hqw.bleproxy.protocol.BleProxy.ScanResult.getDefaultInstance();
        } else {
          scanResultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hqw.bleproxy.protocol.BleProxy.internal_static_com_hqw_bleproxy_protocol_BleProxyMsg_descriptor;
      }

      public com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg getDefaultInstanceForType() {
        return com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg.getDefaultInstance();
      }

      public com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg build() {
        com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg buildPartial() {
        com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg result = new com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (controlBuilder_ == null) {
          result.control_ = control_;
        } else {
          result.control_ = controlBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (scanResultBuilder_ == null) {
          result.scanResult_ = scanResult_;
        } else {
          result.scanResult_ = scanResultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg) {
          return mergeFrom((com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg other) {
        if (other == com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasControl()) {
          mergeControl(other.getControl());
        }
        if (other.hasScanResult()) {
          mergeScanResult(other.getScanResult());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCmd()) {
          
          return false;
        }
        if (hasControl()) {
          if (!getControl().isInitialized()) {
            
            return false;
          }
        }
        if (hasScanResult()) {
          if (!getScanResult().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hqw.bleproxy.protocol.BleProxy.BleProxyMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required .com.hqw.bleproxy.protocol.ProxyMsgCmd cmd = 1;
      private com.hqw.bleproxy.protocol.BleProxy.ProxyMsgCmd cmd_ = com.hqw.bleproxy.protocol.BleProxy.ProxyMsgCmd.CONTROL;
      /**
       * <code>required .com.hqw.bleproxy.protocol.ProxyMsgCmd cmd = 1;</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.hqw.bleproxy.protocol.ProxyMsgCmd cmd = 1;</code>
       */
      public com.hqw.bleproxy.protocol.BleProxy.ProxyMsgCmd getCmd() {
        return cmd_;
      }
      /**
       * <code>required .com.hqw.bleproxy.protocol.ProxyMsgCmd cmd = 1;</code>
       */
      public Builder setCmd(com.hqw.bleproxy.protocol.BleProxy.ProxyMsgCmd value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.hqw.bleproxy.protocol.ProxyMsgCmd cmd = 1;</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = com.hqw.bleproxy.protocol.BleProxy.ProxyMsgCmd.CONTROL;
        onChanged();
        return this;
      }

      // optional .com.hqw.bleproxy.protocol.Control control = 2;
      private com.hqw.bleproxy.protocol.BleProxy.Control control_ = com.hqw.bleproxy.protocol.BleProxy.Control.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.hqw.bleproxy.protocol.BleProxy.Control, com.hqw.bleproxy.protocol.BleProxy.Control.Builder, com.hqw.bleproxy.protocol.BleProxy.ControlOrBuilder> controlBuilder_;
      /**
       * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
       */
      public boolean hasControl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
       */
      public com.hqw.bleproxy.protocol.BleProxy.Control getControl() {
        if (controlBuilder_ == null) {
          return control_;
        } else {
          return controlBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
       */
      public Builder setControl(com.hqw.bleproxy.protocol.BleProxy.Control value) {
        if (controlBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          control_ = value;
          onChanged();
        } else {
          controlBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
       */
      public Builder setControl(
          com.hqw.bleproxy.protocol.BleProxy.Control.Builder builderForValue) {
        if (controlBuilder_ == null) {
          control_ = builderForValue.build();
          onChanged();
        } else {
          controlBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
       */
      public Builder mergeControl(com.hqw.bleproxy.protocol.BleProxy.Control value) {
        if (controlBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              control_ != com.hqw.bleproxy.protocol.BleProxy.Control.getDefaultInstance()) {
            control_ =
              com.hqw.bleproxy.protocol.BleProxy.Control.newBuilder(control_).mergeFrom(value).buildPartial();
          } else {
            control_ = value;
          }
          onChanged();
        } else {
          controlBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
       */
      public Builder clearControl() {
        if (controlBuilder_ == null) {
          control_ = com.hqw.bleproxy.protocol.BleProxy.Control.getDefaultInstance();
          onChanged();
        } else {
          controlBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
       */
      public com.hqw.bleproxy.protocol.BleProxy.Control.Builder getControlBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getControlFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
       */
      public com.hqw.bleproxy.protocol.BleProxy.ControlOrBuilder getControlOrBuilder() {
        if (controlBuilder_ != null) {
          return controlBuilder_.getMessageOrBuilder();
        } else {
          return control_;
        }
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.Control control = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.hqw.bleproxy.protocol.BleProxy.Control, com.hqw.bleproxy.protocol.BleProxy.Control.Builder, com.hqw.bleproxy.protocol.BleProxy.ControlOrBuilder> 
          getControlFieldBuilder() {
        if (controlBuilder_ == null) {
          controlBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.hqw.bleproxy.protocol.BleProxy.Control, com.hqw.bleproxy.protocol.BleProxy.Control.Builder, com.hqw.bleproxy.protocol.BleProxy.ControlOrBuilder>(
                  control_,
                  getParentForChildren(),
                  isClean());
          control_ = null;
        }
        return controlBuilder_;
      }

      // optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;
      private com.hqw.bleproxy.protocol.BleProxy.ScanResult scanResult_ = com.hqw.bleproxy.protocol.BleProxy.ScanResult.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.hqw.bleproxy.protocol.BleProxy.ScanResult, com.hqw.bleproxy.protocol.BleProxy.ScanResult.Builder, com.hqw.bleproxy.protocol.BleProxy.ScanResultOrBuilder> scanResultBuilder_;
      /**
       * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
       */
      public boolean hasScanResult() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
       */
      public com.hqw.bleproxy.protocol.BleProxy.ScanResult getScanResult() {
        if (scanResultBuilder_ == null) {
          return scanResult_;
        } else {
          return scanResultBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
       */
      public Builder setScanResult(com.hqw.bleproxy.protocol.BleProxy.ScanResult value) {
        if (scanResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          scanResult_ = value;
          onChanged();
        } else {
          scanResultBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
       */
      public Builder setScanResult(
          com.hqw.bleproxy.protocol.BleProxy.ScanResult.Builder builderForValue) {
        if (scanResultBuilder_ == null) {
          scanResult_ = builderForValue.build();
          onChanged();
        } else {
          scanResultBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
       */
      public Builder mergeScanResult(com.hqw.bleproxy.protocol.BleProxy.ScanResult value) {
        if (scanResultBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              scanResult_ != com.hqw.bleproxy.protocol.BleProxy.ScanResult.getDefaultInstance()) {
            scanResult_ =
              com.hqw.bleproxy.protocol.BleProxy.ScanResult.newBuilder(scanResult_).mergeFrom(value).buildPartial();
          } else {
            scanResult_ = value;
          }
          onChanged();
        } else {
          scanResultBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
       */
      public Builder clearScanResult() {
        if (scanResultBuilder_ == null) {
          scanResult_ = com.hqw.bleproxy.protocol.BleProxy.ScanResult.getDefaultInstance();
          onChanged();
        } else {
          scanResultBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
       */
      public com.hqw.bleproxy.protocol.BleProxy.ScanResult.Builder getScanResultBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getScanResultFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
       */
      public com.hqw.bleproxy.protocol.BleProxy.ScanResultOrBuilder getScanResultOrBuilder() {
        if (scanResultBuilder_ != null) {
          return scanResultBuilder_.getMessageOrBuilder();
        } else {
          return scanResult_;
        }
      }
      /**
       * <code>optional .com.hqw.bleproxy.protocol.ScanResult scanResult = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.hqw.bleproxy.protocol.BleProxy.ScanResult, com.hqw.bleproxy.protocol.BleProxy.ScanResult.Builder, com.hqw.bleproxy.protocol.BleProxy.ScanResultOrBuilder> 
          getScanResultFieldBuilder() {
        if (scanResultBuilder_ == null) {
          scanResultBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.hqw.bleproxy.protocol.BleProxy.ScanResult, com.hqw.bleproxy.protocol.BleProxy.ScanResult.Builder, com.hqw.bleproxy.protocol.BleProxy.ScanResultOrBuilder>(
                  scanResult_,
                  getParentForChildren(),
                  isClean());
          scanResult_ = null;
        }
        return scanResultBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.hqw.bleproxy.protocol.BleProxyMsg)
    }

    static {
      defaultInstance = new BleProxyMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.hqw.bleproxy.protocol.BleProxyMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hqw_bleproxy_protocol_Control_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hqw_bleproxy_protocol_Control_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hqw_bleproxy_protocol_ScanResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hqw_bleproxy_protocol_ScanResult_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hqw_bleproxy_protocol_BleProxyMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hqw_bleproxy_protocol_BleProxyMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026BleProxyMsg_Java.proto\022\031com.hqw.blepro" +
      "xy.protocol\"=\n\007Control\0222\n\003cmd\030\001 \002(\0162%.co" +
      "m.hqw.bleproxy.protocol.ControlCmd\"9\n\nSc" +
      "anResult\022\014\n\004name\030\001 \002(\t\022\017\n\007address\030\002 \002(\t\022" +
      "\014\n\004rssi\030\003 \002(\005\"\262\001\n\013BleProxyMsg\0223\n\003cmd\030\001 \002" +
      "(\0162&.com.hqw.bleproxy.protocol.ProxyMsgC" +
      "md\0223\n\007control\030\002 \001(\0132\".com.hqw.bleproxy.p" +
      "rotocol.Control\0229\n\nscanResult\030\003 \001(\0132%.co" +
      "m.hqw.bleproxy.protocol.ScanResult*+\n\013Pr" +
      "oxyMsgCmd\022\013\n\007CONTROL\020\001\022\017\n\013SCAN_RESULT\020\002*",
      "F\n\nControlCmd\022\013\n\007TURN_ON\020\000\022\014\n\010TURN_OFF\020\001" +
      "\022\016\n\nSTART_SCAN\020\002\022\r\n\tSTOP_SCAN\020\003B%\n\031com.h" +
      "qw.bleproxy.protocolB\010BleProxy"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_hqw_bleproxy_protocol_Control_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_hqw_bleproxy_protocol_Control_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hqw_bleproxy_protocol_Control_descriptor,
              new java.lang.String[] { "Cmd", });
          internal_static_com_hqw_bleproxy_protocol_ScanResult_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_hqw_bleproxy_protocol_ScanResult_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hqw_bleproxy_protocol_ScanResult_descriptor,
              new java.lang.String[] { "Name", "Address", "Rssi", });
          internal_static_com_hqw_bleproxy_protocol_BleProxyMsg_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_hqw_bleproxy_protocol_BleProxyMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_hqw_bleproxy_protocol_BleProxyMsg_descriptor,
              new java.lang.String[] { "Cmd", "Control", "ScanResult", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
