#-*- coding: utf-8 -*-
from PyQt4.QtCore import SIGNAL

SIG_CONNECT_SERVER    = SIGNAL("SIG_CONNECT_SERVER")
SIG_MSG_RECVED        = SIGNAL("SIG_MSG_RECVED")
SIG_BLE_DEVICE        = SIGNAL("SIG_BLE_DEVICE")
SIG_SCANNING          = SIGNAL("SIG_SCANNING")
SIG_CONNECT_RESULT    = SIGNAL("SIG_CONNECT_RESULT")
SIG_DISCONNECT_BLE    = SIGNAL("SIG_DISCONNECT_BLE")